env = Environment(parse_flags = "-O3 -pedantic -Wall -Wvla -Wold-style-cast -std=c++1y")  # Initialize the environment

env.Append(LIBS = [File('./libjson.a')])

Default(env.Program('main', ['main.cpp']))
